//! NFC card types for the `cards` and `card_details` tables.
//!
//! A **card** (`cards` table) is the physical NFC tag identified by `card_id`.
//! Its **detail** (`card_details` table) tracks the current balance, NFC
//! reference, registration code, hashed password, and network assignment.

use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use utoipa::ToSchema;
use uuid::Uuid;

/// Database row for the `cards` table — NFC card master records.
#[derive(Debug, Serialize, FromRow, ToSchema)]
pub struct Card {
    /// Primary key (`UUID`).
    pub id: Uuid,
    /// Physical NFC card identifier string.
    pub card_id: String,
    /// Current lifecycle status (e.g. `"active"`, `"blocked"`).
    pub status: Option<String>,
}

/// Database row for the `card_details` table — card balance and credentials.
///
/// The `password` field is excluded from JSON serialisation.
#[derive(Debug, Serialize, Deserialize, FromRow, ToSchema)]
pub struct CardDetail {
    /// Primary key (auto-generated by DB default for trigger-based inserts).
    pub id: Uuid,
    /// Current monetary balance on the card.
    pub amount: f64,
    /// NFC reference string (unique, links to `cards.card_id`).
    pub nfc_ref: String,
    /// Customer registration / client code tied to this card.
    pub client_code: String,
    /// Argon2-hashed PIN/password for balance checks (never serialized).
    #[serde(skip_serializing)]
    #[schema(read_only)]
    pub password: Option<String>,
    /// Network assignment code.
    pub network: Option<String>,
}

/// Request body for `POST /api/v1/cards/{nfc_ref}/balance` — password-protected
/// balance inquiry.
#[derive(Debug, Deserialize, ToSchema)]
pub struct BalanceCheckRequest {
    /// Plaintext card password / PIN to verify ownership.
    pub password: String,
}

/// Request body for `POST /api/v1/cards`.
#[derive(Debug, Deserialize, ToSchema)]
pub struct CreateCardRequest {
    /// The physical NFC card identifier to register.
    pub card_id: String,
}

/// Response for a successful balance inquiry.
#[derive(Debug, Serialize, ToSchema)]
pub struct BalanceResponse {
    /// NFC reference string.
    pub nfc_ref: String,
    /// Client registration / code.
    pub client_code: String,
    /// Current balance.
    pub amount: f64,
    /// Network assignment.
    pub network: Option<String>,
}
